# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'player.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Player(object):
    def setupUi(self, Player):
        Player.setObjectName("Player")
        Player.resize(273, 372)
        self.verticalLayout = QtWidgets.QVBoxLayout(Player)
        self.verticalLayout.setObjectName("verticalLayout")
        self.trackname = QtWidgets.QLabel(Player)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trackname.sizePolicy().hasHeightForWidth())
        self.trackname.setSizePolicy(sizePolicy)
        self.trackname.setAlignment(QtCore.Qt.AlignCenter)
        self.trackname.setObjectName("trackname")
        self.verticalLayout.addWidget(self.trackname)
        self.volume_mgmt = QtWidgets.QWidget(Player)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volume_mgmt.sizePolicy().hasHeightForWidth())
        self.volume_mgmt.setSizePolicy(sizePolicy)
        self.volume_mgmt.setObjectName("volume_mgmt")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.volume_mgmt)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.volumeicon = QtWidgets.QToolButton(self.volume_mgmt)
        self.volumeicon.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon.fromTheme("audio-volume-high")
        self.volumeicon.setIcon(icon)
        self.volumeicon.setObjectName("volumeicon")
        self.horizontalLayout_2.addWidget(self.volumeicon)
        self.volume = QtWidgets.QSlider(self.volume_mgmt)
        self.volume.setMinimum(0)
        self.volume.setMaximum(100)
        self.volume.setProperty("value", 100)
        self.volume.setOrientation(QtCore.Qt.Horizontal)
        self.volume.setObjectName("volume")
        self.horizontalLayout_2.addWidget(self.volume)
        self.verticalLayout.addWidget(self.volume_mgmt)
        self.albumpic = QtWidgets.QLabel(Player)
        self.albumpic.setAlignment(QtCore.Qt.AlignCenter)
        self.albumpic.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.albumpic.setObjectName("albumpic")
        self.verticalLayout.addWidget(self.albumpic)
        self.widget = QtWidgets.QWidget(Player)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.trackpos = QtWidgets.QLabel(self.widget)
        self.trackpos.setObjectName("trackpos")
        self.horizontalLayout_3.addWidget(self.trackpos)
        self.slider = QtWidgets.QSlider(self.widget)
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.horizontalLayout_3.addWidget(self.slider)
        self.tracklen = QtWidgets.QLabel(self.widget)
        self.tracklen.setObjectName("tracklen")
        self.horizontalLayout_3.addWidget(self.tracklen)
        self.verticalLayout.addWidget(self.widget)
        self.player_ctl = QtWidgets.QWidget(Player)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.player_ctl.sizePolicy().hasHeightForWidth())
        self.player_ctl.setSizePolicy(sizePolicy)
        self.player_ctl.setObjectName("player_ctl")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.player_ctl)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.shuffle = QtWidgets.QToolButton(self.player_ctl)
        self.shuffle.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon.fromTheme("media-playlist-repeat")
        self.shuffle.setIcon(icon)
        self.shuffle.setObjectName("shuffle")
        self.horizontalLayout.addWidget(self.shuffle)
        self.prevbtn = QtWidgets.QToolButton(self.player_ctl)
        self.prevbtn.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon.fromTheme("media-skip-backward")
        self.prevbtn.setIcon(icon)
        self.prevbtn.setObjectName("prevbtn")
        self.horizontalLayout.addWidget(self.prevbtn)
        self.playbtn = QtWidgets.QToolButton(self.player_ctl)
        self.playbtn.setMinimumSize(QtCore.QSize(55, 55))
        self.playbtn.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon.fromTheme("media-playback-start")
        self.playbtn.setIcon(icon)
        self.playbtn.setObjectName("playbtn")
        self.horizontalLayout.addWidget(self.playbtn)
        self.nextbtn = QtWidgets.QToolButton(self.player_ctl)
        self.nextbtn.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon.fromTheme("media-skip-forward")
        self.nextbtn.setIcon(icon)
        self.nextbtn.setObjectName("nextbtn")
        self.horizontalLayout.addWidget(self.nextbtn)
        self.stopbtn = QtWidgets.QToolButton(self.player_ctl)
        self.stopbtn.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon.fromTheme("media-playback-stop")
        self.stopbtn.setIcon(icon)
        self.stopbtn.setObjectName("stopbtn")
        self.horizontalLayout.addWidget(self.stopbtn)
        self.verticalLayout.addWidget(self.player_ctl)

        self.retranslateUi(Player)
        QtCore.QMetaObject.connectSlotsByName(Player)

    def retranslateUi(self, Player):
        _translate = QtCore.QCoreApplication.translate
        Player.setWindowTitle(_translate("Player", "Form"))
        self.trackname.setText(_translate("Player", "Lorem Ipsum - Dolor Сидит"))
        self.volumeicon.setText(_translate("Player", "..."))
        self.albumpic.setText(_translate("Player", "Обложка альбома"))
        self.trackpos.setText(_translate("Player", "00:00"))
        self.tracklen.setText(_translate("Player", "00:00"))
        self.shuffle.setText(_translate("Player", "..."))
        self.prevbtn.setText(_translate("Player", "..."))
        self.playbtn.setText(_translate("Player", "..."))
        self.nextbtn.setText(_translate("Player", "..."))
        self.stopbtn.setText(_translate("Player", "..."))

